# Generated by Django 3.2.7 on 2021-09-09 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('excerpt', models.TextField(null=True, verbose_name='excerpt')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('published', models.DateTimeField(verbose_name='published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
